version: 0.2
env:
  variables:
    ENV: staging
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip terraform_0.11.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - export current_date=$(date +%F-%s)
      - chmod 700 $CODEBUILD_SRC_DIR/entrypoint
  build:
    commands:
      - docker pull $ECR_REPOSITORY\:latest || true
      - docker build --cache-from=$ECR_REPOSITORY\:latest -t myapp .
      - docker tag myapp:latest $ECR_REPOSITORY\:latest
      - docker tag myapp:latest $ECR_REPOSITORY\:$current_date
      - docker push $ECR_REPOSITORY\:latest
      - docker push $ECR_REPOSITORY\:$current_date
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/terraform-code
      - terraform init && terraform workspace select $ENV
      - TF_VAR_docker_image=$current_date
      - terraform apply -target="aws_ecs_service.ecs_service" --auto-approve
