#!/bin/sh

export AWS_DEFAULT_REGION=us-east-1
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXXX

aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} && \
aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} && \
aws configure set default.region ${AWS_DEFAULT_REGION}


whoami

echo "!!!!!"
mv ~/.aws /var/www/html/
chmod -R 777 /var/www/html/.aws

exec "$@"
